[package]
name = "next_os_installer"
version = "0.1.0"
description = "NextOS Wubi-Style Loop-Mount Installer"
authors = ["NextOS"]
edition = "2021"

[lib]
name = "next_os_installer_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["devtools"] }
tauri-plugin-opener = "2"
tauri-plugin-dialog = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
flate2 = "1"
sha-crypt = { version = "0.6.0", features = ["getrandom"] }

[profile.release]
strip = true
lto = true
codegen-units = 1
opt-level = "z"
